package de.dfki.omm.events;

/**
 * Enumerator of all possible types of {@link OMMEvent}s. 
 */
public enum OMMEventType
{
	UNKNOWN, MEMORY_CREATED, BLOCK_ADDED, BLOCK_REMOVED, 
	PAYLOAD_CHANGED, LINK_CHANGED, METADATA_CHANGED,
	SUBJECT_CHANGED, TITLE_CHANGED, DESCRIPTION_CHANGED, 
	FORMAT_CHANGED, NAMESPACE_CHANGED, TYPE_CHANGED, 
	ENCODING_CHANGED, MEMORY_SYNC
}
